sudo: false
language: python
cache: pip
notifications:
  email: false

matrix:
  include:
    - name: "Linux Â· Python 3.6"
      python: 3.6
      os: linux
      dist: trusty

script: true

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install -e .
  - python setup.py flake8
  - pytest tests --cov=occa

after_success:
  - codecov
